all: ultrasn contus time

ultrasn: ultrasn.cpp
	g++ ultrasn.cpp -o ultrasn -Wall -lwiringPi
	
contus: contus.cpp
	g++ contus.cpp -o contus -Wall -lwiringPi
	
time: time.cpp
	g++ time.cpp -o time -Wall -lwiringPi